library(data.table)
EDA_Elec <- fread(file.choose(), sep = ';', header = TRUE, na.strings = '?')
EDA_Elec_2122 <- EDA_Elec[66638:69517,]
subm1 <- as.numeric(EDA_Elec_2122$Sub_metering_1)
subm2 <- as.numeric(EDA_Elec_2122$Sub_metering_2)
subm3 <- as.numeric(EDA_Elec_2122$Sub_metering_3)
png('./plot3.png', width = 480, height = 480)
xaxislabels = c('Thu', 'Fri', 'Sat')
plot(subm1, type = 'l', xaxt = 'n', ylab = 'Energy Sub meterring')
par(new = F)
lines(subm2, col = 'red')
par(new = F)
lines(subm3, col = 'blue')
par(new = F)
legend('topright', c('Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3'), lty = c(1, 1, 1), col = c('black', 'red', 'blue'))
axis(1, at = c(1:3), labels = xaxislabels)
dev.off()