library(data.table)
EDA_Elec <- fread(file.choose(), sep = ';', header = TRUE, na.strings = '?')
EDA_Elec_2122 <- EDA_Elec[66638:69517,]
GAP <- as.numeric(EDA_Elec_2122$Global_active_power)
subm1 <- as.numeric(EDA_Elec_2122$Sub_metering_1)
subm2 <- as.numeric(EDA_Elec_2122$Sub_metering_2)
subm3 <- as.numeric(EDA_Elec_2122$Sub_metering_3)
Voltage <- as.numeric(EDA_Elec_2122$Voltage)
GRP <- as.numeric(EDA_Elec_2122$Global_reactive_power)
png('./plot4.png', width = 480, height = 480)
par(mfcol=c(2,2))
xaxislabels = c('Thu', 'Fri', 'Sat')
plot(GAP, type = 'l', xaxt = 'n', ylab = 'Global Active Power (kilowatts)')
axis(1, at = c(1:3), labels = xaxislabels)
plot(subm1, type = 'l', xaxt = 'n', ylab = 'Energy Sub meterring')
par(new = F)
lines(subm2, col = 'red')
par(new = F)
lines(subm3, col = 'blue')
par(new = F)
legend('topright', c('Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3'), lty = c(1, 1, 1), col = c('black', 'red', 'blue'))
axis(1, at = c(1:3), labels = xaxislabels)
plot(Voltage, type = 'l', xaxt = 'n', ylab = 'Voltage', xlab = 'datetime')
axis(1, at = c(1:3), labels = xaxislabels)
plot(GRP, type = 'l', xaxt = 'n', ylab = 'Global_reactive_power', xlab = 'datetime')
axis(1, at = c(1:3), labels = xaxislabels)
dev.off()